asas

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -36,3 +36,11 @@ jobs:
           echo test, and deploy your project.
       - name: Test Python version
         run: python --version
+      - name: Run a simple check
+        run: |
+          if [ 1 -eq 2 ]; then
+            echo "Check passed: 1 equals 1"
+          else
+            echo "Check failed: 1 does not equal 1"
+            exit 1
+          fi
